[versions]
packetevents = "2.11.0"
adventure = "4.25.0"
paper = "1.21.11-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
bungeecord = "1.21-R0.5-SNAPSHOT"
sponge = "14.0.0"

shadow = "9.2.2"
run-paper = "3.0.2"
spongeGradle = "2.3.0"

[libraries]
packetevents-api = { group = "com.github.retrooper", name = "packetevents-api", version.ref = "packetevents" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-serializer-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventure-text-serializer-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
bungeecord = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungeecord" }
sponge = { group = "org.spongepowered", name = "spongeapi", version.ref = "sponge" }

[bundles]
adventure = [ "adventure-api" ]
adventure-serializers = [ "adventure-text-serializer-gson", "adventure-text-serializer-legacy" ]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
run-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "run-paper" }
spongeGradle = { id = "org.spongepowered.gradle.plugin", version.ref = "spongeGradle" }