[versions]
paper = "1.21.8-R0.1-SNAPSHOT"
packetevents = "2.11.0"
lombok = "1.18.42"
shadow = "9.0.1"
run-paper = "3.0.2"
configlib = "4.6.1"
lettuce = "6.8.1.RELEASE"
cloud = "2.0.0-beta.14"
expiringmap = "0.5.11"
ormlite = "6.1"
hikaricp = "7.0.2"

# Runtime only
mysql = "9.4.0"
mariadb = "3.5.6"
h2 = "2.4.240"
adventure-text-serializer-plain = "4.25.0"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
packetevents-spigot = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
configlib-yaml = { group = "de.exlll", name = "configlib-yaml", version.ref = "configlib" }
lettuce = { group = "io.lettuce", name = "lettuce-core", version.ref = "lettuce" }
cloud = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud" }
expiringmap = { group = "net.jodah", name = "expiringmap", version.ref = "expiringmap" }
ormlite = { group = "com.j256.ormlite", name = "ormlite-jdbc", version.ref = "ormlite" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }

# Runtime only
mysql = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
adventure-text-serializer-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure-text-serializer-plain" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }