#    ___________     __                   ________                       .___
#    \__    ___/____/  |_  ____   _____  /  _____/ __ _______ _______  __| _/
#      |    | /  _ \   __\/ __ \ /     \/   \  ___|  |  \__  \\_  __ \/ __ |
#      |    |(  <_> )  | \  ___/|  Y Y  \    \_\  \  |  // __ \|  | \/ /_/ |
#      |____| \____/|__|  \___  >__|_|  /\______  /____/(____  /__|  \____ |
#                             \/      \/        \/           \/           \/

# The version of the config file. DO NOT TOUCH!!!
config_version: 1

# What text formatter to use for formatting text (how to read the messages.yml)
# NATIVE: The default legacy Minecraft text serializer.
# MINIMESSAGE: The Kyori MiniMessage text serializer.
formatter: NATIVE